name: Update Languages
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  update-languages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in token for checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Debug LANGUAGES_USED
        run: |
          if [ -z "$LANGUAGES_USED" ]; then
            echo "Error: LANGUAGES_USED is not set."
            exit 1
          else
            echo "LANGUAGES_USED is set."
          fi
        env:
          LANGUAGES_USED: ${{ secrets.LANGUAGES_USED }}

      - name: Run languages script
        env:
          LANGUAGES_USED: ${{ secrets.LANGUAGES_USED }}
        run: |
          python languages_script.py

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update README
        run: |
          cp languages.md README.md
          git add README.md
          git commit -m "Update languages"
          git push